# Generated by Django 3.1 on 2020-09-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200830_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default/default.jpg', upload_to=''),
        ),
    ]
