# Generated by Django 3.1 on 2020-09-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image_content',
            field=models.ImageField(blank=True, upload_to='content/'),
        ),
    ]
