# Generated by Django 3.1 on 2020-09-25 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='likes',
        ),
        migrations.AddField(
            model_name='content',
            name='likes',
            field=models.ManyToManyField(related_name='my_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
